EcomWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminpanel/',include('adminpanel.urls')),
    path('',include('home.urls')),
    
]

home/urls.py
from django.conf import settings
from django.urls import path
from .views import home, sign_up, sign_in, error_page
from django.conf.urls.static import static

app_name = 'home'
urlpatterns = [
    
    path('',home,name='site_home'),
    path('register/',sign_up, name='sign_up'), 
    path('sign_in/',sign_in, name='sign_in'),
    path('404/',error_page)
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(decimal_places = 2,max_digits = 8, default = 0)
    stock = models.IntegerField(default = 0)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render, redirect
from .models import Product, User
from adminpanel.forms import RegistrationForm, LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate,login

# Create your views here.
def home(request):
    products = Product.objects.all()
    return render(request,'home/index.html',{'products':products})

def sign_up(request):
    if request.method=='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Successfully registered')
            return redirect('home:site_home')
    else:
        form =RegistrationForm()
    return render(request,'home/register.html',{'form':form})

def sign_in(request):
    if request.method =='POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username = username, password = password)
            if user is not None:
                login(request,user)
                return redirect('admin_home')
            else:
                messages.error(request,'Invalid Username or Password!!!')
                return redirect('home:sign_in')

    else:
        form = LoginForm()
    return render(request,'home/login.html',{'form':form})

def error_page(request):
    return render(request,'home/404.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" class="navbar " data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home:site_home' %}">KidsPark</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:site_home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:sign_up' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:sign_in' %}">Login</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% if messages %}
      <div>
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                  {{ message }}
              </div>
              <script>
                alert('{{message}}')
              </script>
          {% endfor %}
      </div>
  {% endif %}
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block title %}
KidsPark | Home
{% endblock %}
{% block content %}

<div class="row m-5">
{% for product in products %}
    <div class="col-3 m-5">
        <div class="card" style="width: 18rem; height:500px">
            <img src="{{ product.image.url }}" class="card-img-top" alt="..." width="250px" height="250px">
            <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{product.description}} <br>Rs. {{product.price}}/- <br>
                {% if product.stock != 0 %} 
                   <label style="color: blue;"> Stock {{product.stock}} available</label><br>
                {% else %}
                <label style="color:red">Currently Unavailable!!!</label>
                {% endif %}
                <label class="btn btn-secondary">{{ product.category.name }}</label>
            </p>
            
            
        </p>
              
            </div>
        </div>
    </div>

  {% endfor %}
</div>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base.html' %}
{% block title %}
KidsPark | Login
{% endblock %}
{% block content %}

<div class="row m-5">
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login" class="btn btn-primary"/>
</form>
     
</div>
{% endblock %}

home/templates/home/register.html
{% extends 'home/base.html' %}
{% block title %}
KidsPark | Registration
{% endblock %}
{% block content %}

<div class="row m-5">
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register" class="btn btn-primary"/>
</form>
     
</div>
{% endblock %}